/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FullerineInputPanel.java
 *
 * Created on Feb 16, 2010, 4:28:17 PM
 */

package nano.envnt3D.tools.fullerine;

import java.awt.event.ActionEvent;
import javax.media.j3d.TransformGroup;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import nano.envnt3D.AppearanceNano;
import nano.envnt3D.Coords;
import nano.envnt3D.Interface3D;
import nano.envnt3D.commonElements.Atom;
import nano.envnt3D.commonElements.Bond;
import nano.envnt3D.commonElements.ColorPanel.paneleListener;


/**
 *
 * @author chanaka
 */
public class FullerineInputPanel extends javax.swing.JPanel  {

	int NoOfAtoms,geometry;
	FileAccess f;
        AppearanceNano appearancenano=new AppearanceNano();
        boolean firstClick=true;
    /** Creates new form FullerineInputPanel */
    public FullerineInputPanel() {
        initComponents();


        colorPanel1.addColorEventListener(new paneleListener() {

            @Override
            public void colorChangePerformed(ActionEvent e) {
                //throw new UnsupportedOperationException("Not supported yet.");
                jButton2ActionPerformed(e);
            }

            @Override
            public void radiousChangePerformed(ChangeEvent evt) {
                //throw new UnsupportedOperationException("Not supported yet.");
                jButton2ActionPerformed(null);
            }
        });

        colorPanel2.addColorEventListener(new paneleListener() {

            @Override
            public void colorChangePerformed(ActionEvent e) {
                //throw new UnsupportedOperationException("Not supported yet.");
                jButton2ActionPerformed(e);
            }

            @Override
            public void radiousChangePerformed(ChangeEvent evt) {
                //throw new UnsupportedOperationException("Not supported yet.");
                jButton2ActionPerformed(null);
            }
        });
        
         f =new FileAccess();
        try {
			int[] flist =  f.getFullerines();
			for(int fullerine : flist ){
				jComboBox1.addItem("C-"+fullerine);
			}
			
			String selected = jComboBox1.getSelectedItem().toString().substring(2);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			//e.printStackTrace();
			JOptionPane.showMessageDialog(null, "Fullerine library not found. Copy the 'FullerineLib' folder in to project folder");
		//	JOptionPane.showInternalMessageDialog(null, "There is an error in file ", "Error",JOptionPane.OK_OPTION);
		}
        
        

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        colorPanel1 = new nano.envnt3D.commonElements.ColorPanel.ColorPanel();
        colorPanel2 = new nano.envnt3D.commonElements.ColorPanel.ColorPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(300, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Select the number of carbon atoms");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 250, 27));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 117, -1));

        jLabel2.setText("Available other geometries");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 27));

        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 116, -1));

        jButton2.setText("Show");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        colorPanel1.setRGBColor(new java.awt.Color(221, 69, 59));
        colorPanel1.setRadius(20.0F);
        add(colorPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        colorPanel2.setRGBColor(new java.awt.Color(226, 223, 188));
        add(colorPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 276, 280, 0));

        jLabel3.setText("Atom");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel4.setText("Bond");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    	jComboBox2.removeAllItems();
    	String selected = jComboBox1.getSelectedItem().toString().substring(2);
    	NoOfAtoms = Integer.parseInt(selected);
    	try {
			int[] geometries = f.getGeometries(NoOfAtoms);
			for(int geometry : geometries){
			jComboBox2.addItem("Geometry "+geometry);
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			JOptionPane.showMessageDialog(null, "Fullerine library not found. Copy the 'FullerineLib' folder in to project folder");
		}
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
    	Fullerines f;
    	if(jComboBox2.getSelectedItem()!=null) {
    		String gm = jComboBox2.getSelectedItem().toString().split(" ")[1];
    		geometry = Integer.parseInt(gm);
    		f = new Fullerines(NoOfAtoms, geometry);
    		//System.out.println(geometry+","+NoOfAtoms);
    	}
    	else{
    		f = new Fullerines(NoOfAtoms);
    		//System.out.println(NoOfAtoms);
    	}
    	double[][] atomCoords = f.getAtomCoordinates();
    	double[][] bondCoords = f.getBondCoordinates();
          

    	
        TransformGroup atomsGroup,bondsGroup;
        Atom atom=new Atom();
        atomsGroup=atom.drawAtoms(atomCoords,appearancenano.setMatColor(colorPanel1.getRGBColor()),colorPanel1.getRadius()/100);


		    	Bond bond=new Bond();
		    	bondsGroup=bond.drawBonds(bondCoords,appearancenano.setMatColor(colorPanel2.getRGBColor()),colorPanel2.getRadius()/100);

        TransformGroup[] TG={atomsGroup,bondsGroup};
        if (firstClick){
                            firstClick=false;
                        } else{
                            Interface3D.removeLastBG();
                        }
                        Interface3D.createBG(TG);
                        Interface3D.displayLastBG();
    	//atoms full = new atoms(atomCoords,bondCoords);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private nano.envnt3D.commonElements.ColorPanel.ColorPanel colorPanel1;
    private nano.envnt3D.commonElements.ColorPanel.ColorPanel colorPanel2;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
