/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Gipanel.java
 *
 * Created on Mar 8, 2010, 10:29:16 AM
 */

package nano.envnt3D.tools.EnergyBands;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author chanaka
 */
public class Gipanel extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	public javax.swing.JTextField ccText,gammaText,sText,epsText;
//	GraphenePlotPanel graphenplot=new GraphenePlotPanel();
	/** Creates new form Gipanel */
    public Gipanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ccText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        gammaText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        epsText = new javax.swing.JTextField();
        plotBut = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 13)); // NOI18N
        jLabel1.setText("Set parameters of the ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 25));

        jLabel2.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 13)); // NOI18N
        jLabel2.setText("graphene bandstructure");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel3.setText("C-C bond length in A:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 170, 25));

        ccText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccTextActionPerformed(evt);
            }
        });
        add(ccText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 106, -1));

        jLabel4.setFont(new java.awt.Font("Bitstream Vera Sans", 2, 13)); // NOI18N
        jLabel4.setText("(Default is 1.42)");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 151, -1));

        jLabel5.setText("C-C transfer energy in eV:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 220, 25));

        jLabel6.setFont(new java.awt.Font("Bitstream Vera Sans", 2, 13)); // NOI18N
        jLabel6.setText("(Default is 3.013)");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 120, -1));

        gammaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gammaTextActionPerformed(evt);
            }
        });
        add(gammaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 106, -1));

        jLabel8.setText("Set the overlap integral ");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 25));

        jLabel10.setFont(new java.awt.Font("Bitstream Vera Sans", 2, 13)); // NOI18N
        jLabel10.setText("(Default is 0.129)");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 194, -1));

        sText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sTextActionPerformed(evt);
            }
        });
        add(sText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 106, -1));

        jLabel11.setText("Set site energy of 2p orbital");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, 25));

        jLabel13.setFont(new java.awt.Font("Bitstream Vera Sans", 2, 13)); // NOI18N
        jLabel13.setText("(Default is 0)");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 194, -1));

        epsText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                epsTextActionPerformed(evt);
            }
        });
        add(epsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 106, -1));

        plotBut.setText("Plot the Graph");
        add(plotBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 560, 150, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 223, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 304, 220, -1));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 223, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 223, -1));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 222, 10));

        jLabel14.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 13)); // NOI18N
        jLabel14.setText("plot");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void ccTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccTextActionPerformed

    private void gammaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gammaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gammaTextActionPerformed

    private void sTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sTextActionPerformed

    private void epsTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_epsTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_epsTextActionPerformed

    public String getccText(){
        return ccText.getText();

    }
    public String getepsText(){
        return epsText.getText();

    }
    public String getgammaText(){
        return gammaText.getText();

    }
    public String getsText(){
        return sText.getText();

    }

    public void setccText(String cc){
         ccText.setText(cc);

    }
    public void setepsText(String eps){
         epsText.setText(eps);

    }
    public void setgammaText(String gamma){
         gammaText.setText(gamma);

    }
    public void setsText(String s){
         sText.setText(s);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    public javax.swing.JButton plotBut;
    // End of variables declaration//GEN-END:variables

}
