/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SwntiPanel.java
 *
 * Created on Mar 10, 2010, 10:52:18 AM
 */

package nano.envnt3D.tools.EnergyBands;

/**
 *
 * @author chanaka
 */
public class SwntiPanel extends javax.swing.JPanel {

    /** Creates new form SwntiPanel */
   public javax.swing.JTextField ccText,gammaText,sText,epsText;
  // public javax.swing.JLabel mLabel;
  // public javax.swing.JLabel nLable;
  // public javax.swing.JButton plotBut;

    public SwntiPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
       ccText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        gammaText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        epsText = new javax.swing.JTextField();
        plotBut = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        mLabel = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        nLable = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 13));
        jLabel1.setText("Set parameters of the ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, 19));

        jLabel5.setText("C-C transfer energy in eV:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 249, 215, 25));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 126, 223, -1));

        ccText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccTextActionPerformed(evt);
            }
        });
        add(ccText, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 198, 106, -1));

        jLabel3.setText("C-C bond length in angstroms:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 144, 232, 25));

        jLabel2.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 13));
        jLabel2.setText("nanotube bandstructure");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 37, 243, -1));

        jLabel4.setFont(new java.awt.Font("Bitstream Vera Sans", 2, 13));
        jLabel4.setText("(Default is 1.42)");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 175, 151, -1));

        jLabel6.setFont(new java.awt.Font("Bitstream Vera Sans", 2, 13));
        jLabel6.setText("(Default is 3.013)");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 280, 194, -1));

        gammaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gammaTextActionPerformed(evt);
            }
        });
        add(gammaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 315, 106, -1));

        jLabel8.setText("Set the overlap integral ");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 363, -1, 25));

        jLabel10.setFont(new java.awt.Font("Bitstream Vera Sans", 2, 13));
        jLabel10.setText("(Default is 0)");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 394, 194, -1));

        sText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sTextActionPerformed(evt);
            }
        });
        add(sText, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 414, 106, -1));

        jLabel11.setText("Set site energy of 2p orbital");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 465, -1, 25));

        jLabel13.setFont(new java.awt.Font("Bitstream Vera Sans", 2, 13));
        jLabel13.setText("(Default is 0)");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 496, 194, -1));

        epsText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                epsTextActionPerformed(evt);
            }
        });
        add(epsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 525, 106, -1));

        plotBut.setText("Plot the Graph");
        add(plotBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 586, 169, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 237, 223, -1));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 348, 223, -1));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 453, 223, -1));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 564, 222, 10));

        jLabel14.setText("m=");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 83, -1, 37));
        add(mLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 26, 21));

        jLabel15.setText("and   n=");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 83, -1, 37));
        add(nLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 90, 30, 21));

        jLabel16.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 13));
        jLabel16.setText("plot with");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 60, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void ccTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccTextActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_ccTextActionPerformed

    private void gammaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gammaTextActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_gammaTextActionPerformed

    private void sTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sTextActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_sTextActionPerformed

    private void epsTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_epsTextActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_epsTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    public javax.swing.JLabel mLabel;
    public javax.swing.JLabel nLable;
    public javax.swing.JButton plotBut;
    // End of variables declaration//GEN-END:variables

}
