/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * swntPanel.java
 *
 * Created on Jan 26, 2010, 9:43:02 PM
 */
package nano.envnt3D.tools.swnt;

import com.sun.j3d.utils.universe.SimpleUniverse;
import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.media.j3d.BranchGroup;
import javax.media.j3d.TransformGroup;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.event.ChangeEvent;
import nano.envnt3D.AppearanceNano;
import nano.envnt3D.Coords;
import nano.envnt3D.Interface3D;
import nano.envnt3D.commonElements.Atom;
import nano.envnt3D.commonElements.Bond;



import nano.envnt3D.commonElements.ColorPanel.paneleListener;
import nano.envnt3D.tools.EnergyBands.SwntPanel;
import nano.envnt3D.tools.NanoGUI;
import nano.envnt3D.tools.swnt.swnt.nanotube;

/**
 *
 * @author mufthas
 */
public class GUINanotube extends javax.swing.JPanel {

    /** Creates new form swntPanel */
    JPanel cards; //a panel that uses CardLayout
    BranchGroup BG;
    private JPanel panelButton = new JPanel();
    double[][] coords_bond;
    double[][] coords_atom;
    private TransformGroup atomsGroup, bondsGroup;
    SimpleUniverse simpleu;
    JPanel panelFunction;
    JTextField textM, textN, textL;
    AppearanceNano appearancenano = new AppearanceNano();
    Color cA = Color.YELLOW;
    Color cB = Color.RED;
    int buttonNo = 0;
    boolean firstClick = true;
    SwntPanel swntpanel = new SwntPanel();

    public GUINanotube() {


        initComponents();

        colorPanel1.addColorEventListener(new paneleListener() {

            @Override
            public void colorChangePerformed(ActionEvent e) {
                //throw new UnsupportedOperationException("Not supported yet.");
                jButton1ActionPerformed(e);
            }

            @Override
            public void radiousChangePerformed(ChangeEvent evt) {
                //throw new UnsupportedOperationException("Not supported yet.");
                jButton1ActionPerformed(null);
            }
        });

        colorPanel2.addColorEventListener(new paneleListener() {

            @Override
            public void colorChangePerformed(ActionEvent e) {
                //throw new UnsupportedOperationException("Not supported yet.");
                jButton1ActionPerformed(e);

            }

            @Override
            public void radiousChangePerformed(ChangeEvent evt) {
                //throw new UnsupportedOperationException("Not supported yet.");
                jButton1ActionPerformed(null);
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        colorPanel1 = new nano.envnt3D.commonElements.ColorPanel.ColorPanel();
        jPanel3 = new javax.swing.JPanel();
        colorPanel2 = new nano.envnt3D.commonElements.ColorPanel.ColorPanel();

        setPreferredSize(new java.awt.Dimension(300, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 16));
        jLabel4.setText("Carbon Nano Tube");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        jCheckBox1.setBackground(new java.awt.Color(233, 229, 207));
        jCheckBox1.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jCheckBox1.setText("Show Electrical Properties");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });
        add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 612, -1, -1));

        jPanel1.setBackground(new java.awt.Color(243, 229, 229));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Properties"));

        jLabel2.setText("N");

        jTextField2.setText("5");

        jTextField3.setText("10");

        jLabel1.setText("M");

        jTextField1.setText("5");

        jLabel3.setText("Length");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                .addComponent(jTextField2))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 45, -1, -1));

        jPanel2.setBackground(new java.awt.Color(237, 235, 221));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Atom"));

        colorPanel1.setBackground(new java.awt.Color(237, 235, 221));
        colorPanel1.setRGBColor(new java.awt.Color(141, 171, 173));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(colorPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(colorPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        colorPanel1.getAccessibleContext().setAccessibleParent(jPanel2);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 260, 120));

        jPanel3.setBackground(new java.awt.Color(237, 235, 221));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Bond"));

        colorPanel2.setBackground(new java.awt.Color(237, 235, 221));
        colorPanel2.setRGBColor(new java.awt.Color(235, 223, 30));
        colorPanel2.setLabel("Thickness");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(colorPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(colorPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 260, 120));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //simpleu.getLocale().removeBranchGraph(BG);

        if (jCheckBox1.isSelected())
            jCheckBox1.setSelected(false);


        nanotube nano = new nanotube(Integer.parseInt(jTextField1.getText()), Integer.parseInt(jTextField2.getText()), Integer.parseInt(jTextField3.getText()));
        coords_atom = nano.getCoordinates();
        coords_bond = nano.getBondCoordinates();
        Coords coords = new Coords();
        coords_atom = coords.adjustCoordsToCenter(coords_atom);
        coords_bond = coords.adjustCoordsToCenter(coords_bond);



        Atom atom = new Atom();
        atomsGroup = atom.drawAtoms(coords_atom, appearancenano.setMatColor(colorPanel1.getRGBColor()), colorPanel1.getRadius() / 100);


        Bond bond = new Bond();
        bondsGroup = bond.drawBonds(coords_bond, appearancenano.setMatColor(colorPanel2.getRGBColor()), colorPanel2.getRadius() / 100);



        //simpleu.addBranchGraph(BG);
        //Interface3D.addBG(BG);
        TransformGroup[] TG = {atomsGroup, bondsGroup};

        if (firstClick) {
            firstClick = false;
        } else {
            Interface3D.removeLastBG();
        }
        Interface3D.createBG(TG);
        Interface3D.displayLastBG();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        // TODO add your handling code here:
        if (jCheckBox1.isSelected()) {
            
            Interface3D.setSizeofCanvas(0, 0);
            NanoGUI.setJPanelM(swntpanel.setMN(Integer.parseInt(jTextField1.getText()), Integer.parseInt(jTextField2.getText())));
           // swntpanel.updateUI();
         }else{
            
            Interface3D.setSizeofCanvas();
            NanoGUI.setJPanelM(Interface3D.getcanvas3D());
        }

    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    public JPanel getPanel() {
        return this;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private nano.envnt3D.commonElements.ColorPanel.ColorPanel colorPanel1;
    private nano.envnt3D.commonElements.ColorPanel.ColorPanel colorPanel2;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
